library(readr)
library(readxl)
library(lattice)
library(zoo)
library(quadprog)
library(tseries)
library(urca)
library(vars)
library(ccgarch)
library(fGarch)
library(MASS)
library(FinTS)
library(TTR)
library(fUnitRoots)
library(lmtest)
library(np)                                  
library(quantreg)
library(quantreg)
library(psych)
library(frequencyConnectedness)
pgd <- read_csv("XAUCRY.csv")
#openx <-with(pgd,open)
#open_y <- with(pgd,Open)
openx <-with(pgd,Open)
describe(diff(log(openx))*10)

