library(readr)
library(readxl)
library(lattice)
library(zoo)
library(quadprog)
library(tseries)
library(urca)
library(vars)
library(ccgarch)
library(fGarch)
library(MASS)
library(FinTS)
library(TTR)
library(fUnitRoots)
library(lmtest)
library(np)
library(quantreg)
library(quantreg)
library(psych)
pgd <- read_csv("LBMA_datatd.csv")
#openx <-with(pgd,open)
#open_y <- with(pgd,Open)
openx <-with(pgd,Open_x)
open_y <- with(pgd,Open_y)
openxl<-log(openx)
open_yl<-log(open_y)
y=cbind(openxl,open_yl)
pdshare(y,override.lags = NULL, lag.max = 10)

