library(readr)
library(readxl)
library(lattice)
library(zoo)
library(quadprog)
library(tseries)
library(urca)
library(vars)
library(ccgarch)
library(fGarch)
library(MASS)
library(FinTS)
library(TTR)
library(fUnitRoots)
library(lmtest)
library(np)
library(quantreg)
library(quantreg)
library(psych)
library(frequencyConnectedness)

data(exampleSim)
# Shorten the data, rolling estimation takes quite some time
exampleSim <- exampleSim[1:600,]
pgd <- read_csv("LBMA_datatd.csv")
#openx <-with(pgd,open)
#open_y <- with(pgd,Open)
openx <-with(pgd,Open_x)
open_y <- with(pgd,Open_y)
open_z <- with(pgd,Open)
openxl<-log(openx)
open_yl<-log(open_y)
open_zl<-log(open_y)
y <- data.frame(y1=openxl,y2=open_yl) 
#array(NA,c(32487,3))
#dimnames(y ) <- ('y1' 'y2' 'y3')
#y[,1]<-openxl
#y[,2]<-open_yl
#y[,3]<-open_yl

#exampleSim<-cbind(y,open_zl)
est <- VAR(y, p = 10, type = "const")
spilloverDY12(est, n.ahead = 100, no.corr = F)
sp <- spilloverRollingDY12(y, n.ahead = 100, no.corr = F, "VAR", params_est = params_est, window = 3600)
