library(readr)
library(readxl)
library(lattice)
library(zoo)
library(quadprog)
library(tseries)
library(urca)
library(vars)
library(ccgarch)
library(fGarch)
library(MASS)
library(FinTS)
library(TTR)
library(fUnitRoots)
library(lmtest)
library(np)
library(quantreg)
library(quantreg)
library(psych)
pgd <- read_csv("shfe_autd321.csv")
openx <-with(pgd,Open_x)
open_y <- with(pgd,Open_y)
closex <-with(pgd,Close_x)
close_y <- with(pgd,Close_y)

openxlr<-log(closex)-log(openx)
open_ylr<-log(close_y)-log(open_y)
describe(open_ylr)
describe(openxlr)
y=cbind(openxlr,open_ylr)
vartest1 = VAR(y,p = 5,lag.max=100)
irff =irf(vartest1, impulse = NULL, response = NULL, n.ahead = 10,
          ortho = TRUE, cumulative = FALSE, boot = TRUE, ci = 0.95,
          runs = 100, seed = NULL)
plot(irff)

